name: Jekyll Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source
      uses: actions/checkout@v2

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '2.7'

    - name: Install dependencies
      run: |
        gem install bundler
        bundle install

    - name: Build the site
      run: bundle exec jekyll build

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./_site
- name: gemfile-diff
  # You may pin to the exact commit or the version.
  # uses: r7kamura/gemfile-diff@a63db41e3aa0ed38f33c202c705749a730a14f4b
  uses: r7kamura/gemfile-diff@v0.1.0
  with:
    # Path to Gemfile.lock.
    gemfile_lock_a: 
    # Path to Gemfile.lock.
    gemfile_lock_b: 
    # Space-separated ignored gem names list. Gem written here are ignored even if there are differences.
    ignore: # optional
